stages:
  preprocess:
    cmd: python src/step1_to_s3.py  
  
  enrich:
    cmd: 
    - python src/step2_to_sql.py
    - python src/step3_to_mongo.py  
    
  index:
    cmd: python step4_index_el.py
  
  log:
    cmd: python step4_index_el.py
    outs:
      - pipeline_log.log  
